# Generated by Django 4.0.6 on 2022-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_app', '0002_bot_bot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('src', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ('name',), 'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
    ]
